name: auto_check_SF

on:
  push:
    branches:
      - master
  watch:
    types: started
  schedule:
    - cron: 0 23 * * *
    - cron: 0 4 * * *
    - cron: 0 9 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: TimeZone
        run: |
          sudo cp /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
          date -R
      - name: Checkout
        uses: actions/checkout@main
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Install extensions
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
          sudo add-apt-repository ppa:alex-p/tesseract-ocr
      - name: Install Chrome
        run: |
          curl https://intoli.com/install-google-chrome.sh | bash
          google-chrome --version
          google-chrome --headless --hide-scrollbars --remote-debugging-port=9222 --disable-gpu &
      - name: Run program
        env:
          UID: ${{ secrets.UID }}
          PASSWD: ${{ secrets.PASSWD }}
          APP_ID: ${{ secrets.APP_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          STDNAME: ${{secrets.STDNAME}}
          MOBILE: ${{secrets.MOBILE}}
        run: |
          python3 sufe_check.py -uid ${UID} -passwd ${PASSWD} -os_type "linux" -stdName ${STDNAME} -mobile ${MOBILE} -decoder "baidu" -app_id ${APP_ID} -api_key ${API_KEY} -secret_key ${SECRET_KEY}
      - name: Upload form_dir
        uses: actions/upload-artifact@main
        with:
          name: form_dir
          path: form_dir